# Generated by Django 5.0.1 on 2024-04-18 22:00

import django.db.models.deletion
import homebrew.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homebrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homebrew_images')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homebrew', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('homebrew_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homebrew.homebrew')),
                ('weapon_skill', models.IntegerField(validators=[homebrew.models.Career.validate_main_profile])),
                ('balistic_skill', models.IntegerField(validators=[homebrew.models.Career.validate_main_profile])),
                ('strength', models.IntegerField(validators=[homebrew.models.Career.validate_main_profile])),
                ('toughness', models.IntegerField(validators=[homebrew.models.Career.validate_main_profile])),
                ('agility', models.IntegerField(validators=[homebrew.models.Career.validate_main_profile])),
                ('intelligence', models.IntegerField(validators=[homebrew.models.Career.validate_main_profile])),
                ('will_power', models.IntegerField(validators=[homebrew.models.Career.validate_main_profile])),
                ('fellowship', models.IntegerField(validators=[homebrew.models.Career.validate_main_profile])),
                ('attacks', models.IntegerField()),
                ('wounds', models.IntegerField()),
                ('strength_bonus', models.IntegerField()),
                ('toughness_bonus', models.IntegerField()),
                ('movement', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('insanity_points', models.IntegerField()),
                ('fate_points', models.IntegerField()),
                ('skills', models.TextField()),
                ('talents', models.TextField()),
                ('trappings', models.TextField()),
                ('career_entries', models.TextField()),
                ('career_exits', models.TextField()),
            ],
            bases=('homebrew.homebrew',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('homebrew_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homebrew.homebrew')),
                ('value', models.IntegerField()),
                ('coinage', models.TextField(choices=[('GC', 'Gold Crowns'), ('S', 'Shillings'), ('P', 'Pence')], default='GC')),
            ],
            bases=('homebrew.homebrew',),
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homebrew.item')),
                ('armor_points', models.IntegerField()),
                ('location_covered', models.TextField(choices=[('Head', 'Head'), ('Body', 'Body'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('All', 'All')], default='All')),
            ],
            bases=('homebrew.item',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homebrew.item')),
                ('primary_stat', models.TextField(choices=[('SB', 'Strength Base'), ('TB', 'Toghness Base'), ('Mag', 'Magic'), ('IP', 'Insanity Points'), ('FP', 'Fate Points'), ('A', 'Attacks'), ('M', 'Movement'), ('W', 'Wounds')], default='SB')),
                ('multiplayer', models.IntegerField()),
                ('modifier', models.IntegerField(blank=True, null=True)),
            ],
            bases=('homebrew.item',),
        ),
    ]
